name: CI devops 2024

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and test with Maven
        # working-directory: ./tp1/api/simple-api-student-main
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=SandroSpina698_test-github-actions -Dsonar.organization=sandrospina698 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./tp1/api/simple-api-student-main/pom.xml

  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend  # Assurez-vous que ce job dépend du job de test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push db image
        uses: docker/build-push-action@v3
        with:
          context: ./tp1  # Chemin vers le dossier contenant le Dockerfile du backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-db:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Pousse l'image seulement si le commit est sur la branche main
        
      - name: Build and push httpd image
        uses: docker/build-push-action@v3
        with:
          context: ./tp1/api/httpserver  # Chemin vers le dossier contenant le Dockerfile du backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./tp1/api  # Chemin vers le dossier contenant le Dockerfile du backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}
